### ISSUE TITLE
Two small questions

### ISSUE THREAD

**Issue by leochou0729** [Ravbug/wxWidgetsTemplate#1]
Hello,
  Thanks a lot for creating such a great project. I'm new to wxWidgets. Could I ask you two small questions?
  1. I cannot find any solution file for wxWidgets samples. Do I need to create them for each sample from their project files? I have no idea how to build them all in once.
  2. I have a console app, which loads a DLL in run time. I need to implement UI in the DLL. The console app is running in the background and cannot terminated by users. The DLL need to add a taskbar icon in Windows system tray with some context menu items. I found this snippet on the wiki page.
```
class MyApp: public wxApp
{
public:
    bool OnInit()
    {
        wxDialog* dlg = new wxDialog(NULL, -1,
            "Hello World From Library", wxDefaultPosition, wxDefaultSize,
            wxDEFAULT_DIALOG_STYLE, wxDialogNameStr);
        dlg->Show();
        return true;
    }
};

static wxAppConsole *wxCreateApp()
{
    wxAppConsole::CheckBuildOptions(WX_BUILD_OPTIONS_SIGNATURE, "my app");
    return new MyApp;
}

// The only public function, declared also in library's header.
void RunApp()
{
    wxApp::SetInitializerFunction(wxCreateApp);
    wxEntry(0,NULL);
}
```

I'm not sure if it's the correct way to implement UI with the lastest 3.1.3 version. There are too many different information on the web. Thanks!

**Comment by Ravbug** [comment]
Hi,

Sorry about the late response. Regarding your questions:
1. The samples can be built with make. See the wxWidgets documentation for details.

2. The way you have your main class set up is not familiar to me - did you modify the main.cpp this template provides or create your own? In either case, the wxWidgets forums are a much better place to ask questions regarding wx itself. 

Hope this helps
