### ISSUE TITLE
[BUG] Linking fails on ubuntu 18.04

### ISSUE THREAD

**Issue by DontBreakAlex** [Ravbug/wxWidgetsTemplate#2]
**Describe the bug**
Linking fails under Ubuntu 18.04

**To Reproduce**
`make run`

**Expected behavior**
The linking should succeed 

**Screenshots and/or logs**

``g++ `wxWidgets/build/linux/wx-config --cppflags` `wxWidgets/build/linux/wx-config --libs` -Wl,-rpath,wxWidgets/build/linux/lib/ -g -o linux-build/wxWidgetsTemplate linux-build/interface_derived.o linux-build/interface.o linux-build/main.o`` does not work. 
Wxwidgets wiki says the the config should be at the end of the g++ command. This command works:
``g++ -Wl,-rpath,wxWidgets/build/linux/lib/ -g -o linux-build/wxWidgetsTemplate linux-build/interface_derived.o linux-build/interface.o linux-build/main.o `wxWidgets/build/linux/wx-config --cppflags` `wxWidgets/build/linux/wx-config --libs` ``

**Computer information:**
 - OS: Ubuntu 18.04
 - Compiler version: g++ 9
 - wxWidgets version: 3.1.2

**Comment by DontBreakAlex** [comment]
A fix is to rearrange the variables in the makefile this way:
`$(CC) $(mode) -o $@ $^ $(CFLAGS)` (line 35)
It works for me, but I'm not sure if it will break other platforms.

**Comment by Ravbug** [comment]
Hi, thank you so much for your report! I have incorporated your fix into the makefile and also enabled static linking for Linux. Tested on Ubuntu 18.0.4 and Fedora Linux 30.
